### ISSUE TITLE
Can we use this for learning or other...MIT license?

### ISSUE THREAD

**Issue by ghost** [kosua20/PRPViewer#3]
Nice work, I did a quick look for a license and found a few MIT, is it safe to say your work here is MIT as well? thanks for your time!

**Comment by kosua20** [comment]
Hello !
Libraries in src/libs and external/glfw are under their own license (most of the time MIT) and remain under these licenses.
This work relies a lot on the awesome [libhsplasma](https://github.com/H-uru/libhsplasma), which is [under the GPLv3 license](https://github.com/H-uru/libhsplasma/blob/master/COPYING) and requires PRPViewer to use the same license.

Thank you for asking, I'll update the repo to clarify this.
